#!/usr/bin/env python3
"""
Regenerate agent/article-knowledge.json — a compact knowledge card per site
article/guide, used by the Home Energy Adviser (netlify/functions/decarb-agent.js).

Stdlib only (no pip installs), so it runs in any environment. Resolves paths
relative to this script, so it works from cron/scheduled tasks too.

Run:  python3 scripts/build-article-knowledge.py
Then commit agent/article-knowledge.json in the normal deploy.
"""
import os, re, glob, json, html
from datetime import date

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE = "https://decarbonarma.com/"

EXTRA = ["uk-grants-guide.html", "heat-pump-installation-cost.html", "uk-nuclear-power-2026.html"]
BOILER = ["all rights reserved", "helping uk homeowners", "cookie", "sign up",
          "subscribe", "©", "back to decarbonarma", "read article"]

def clean(s):
    return re.sub(r"\s+", " ", html.unescape(s or "")).strip()

def strip_tags(s):
    return clean(re.sub(r"<[^>]+>", " ", s or ""))

def first(pattern, text, flags=re.I | re.S):
    m = re.search(pattern, text, flags)
    return m.group(1) if m else ""

def build_card(path):
    with open(path, encoding="utf-8", errors="ignore") as fh:
        htmltext = fh.read()
    title = clean(strip_tags(first(r"<title[^>]*>(.*?)</title>", htmltext)))
    title = re.sub(r"\s*[|–—\-·]\s*Decarbonarma.*$", "", title).strip()
    meta = clean(first(r'<meta\s+name=["\']description["\']\s+content=["\'](.*?)["\']', htmltext))
    paras = []
    for m in re.finditer(r"<p\b[^>]*>(.*?)</p>", htmltext, re.I | re.S):
        t = strip_tags(m.group(1))
        if len(t) < 55:
            continue
        low = t.lower()
        if any(b in low for b in BOILER):
            continue
        paras.append(t)
    body = " ".join(paras)
    summary = (meta + " — " + body) if (meta and body) else (meta or body)
    summary = clean(summary)[:600].rsplit(" ", 1)[0]
    if not title or len(summary) < 40:
        return None
    rel = os.path.relpath(path, ROOT).replace(os.sep, "/")
    return {"title": title, "url": BASE + rel, "summary": summary}

def main():
    files = sorted(glob.glob(os.path.join(ROOT, "articles", "*.html")))
    files += [os.path.join(ROOT, e) for e in EXTRA if os.path.exists(os.path.join(ROOT, e))]
    cards = [c for c in (build_card(f) for f in files) if c]
    out = {
        "_meta": {
            "purpose": "Compact knowledge cards for every Decarbonarma article + key guides. The agent reasons over these and links users to the most relevant piece. Summaries only (not full text). Auto-regenerated by scripts/build-article-knowledge.py.",
            "generated": date.today().isoformat(),
            "count": len(cards),
        },
        "articles": cards,
    }
    outpath = os.path.join(ROOT, "agent", "article-knowledge.json")
    with open(outpath, "w", encoding="utf-8") as fh:
        json.dump(out, fh, ensure_ascii=False, indent=1)
    print(f"wrote {len(cards)} cards -> {os.path.relpath(outpath, ROOT)} (generated {out['_meta']['generated']})")

if __name__ == "__main__":
    main()
